apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: application-logs-binding
subjects:
- kind: ServiceAccount
  name: logging-sa
  namespace: openshift-logging
roleRef:
  kind: ClusterRole
  name: collect-application-logs #allows us to collect app logs
  apiGroup: rbac.authorization.k8s.io